name: Update hosts

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          bash domain2ip.sh
          ls -al
          git config --local user.email "sengshinlee@gmail.com"
          git config --local user.name "Sengshin Lee"
          git status
          git add .
          ls -al
          git status
          [ $(git status | grep "new file" | wc -l) -ne 0 ] && git commit -m "Update time: $(date)."; git push -u origin master
          git status
