name: Update hosts

on:
  push:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        run: |
          bash domain2ip.sh
          bash index.sh
          git config --local user.email "sengshinlee@gmail.com"
          git config --local user.name "Sengshin Lee"
          echo "Before"
          git status
          git add .
          echo "After"
          git status
          if [ $(git status | wc -l) -ne 2 ]; then
              git commit -m "Update time: $(date)."
              git push -u origin main
          fi
